ProjectName: ServerlessAPI
ProjectDesc: Serverless to OpenAPI 3.0 specs
ApiGatewayName: serverless-example
DeploymentRegion: eu-central-1
AWSProfile: proto-eu-central-1
Mappings:
  Functions:
    'get-pets-list':
      ServiceLang: javascript
      ServiceName: pets-service
      ServiceTag: serverless-converted
      ServiceModel: pets
      ResourcePath: pets
      ResourceMethod: post
      ServiceResources:
        - Value: dynamodb.yaml
        - Value: my-sns.yaml
      ServicePolicies:
        - Value: my-extra-policy.yaml