ProjectName: ServerlessAPI
ProjectDesc: Serverless to OpenAPI 3.0 specs
ApiGatewayName: serverless-example
DeploymentName: serverless-demo
DeploymentRegion: eu-west-1
AWSProfile: simplify-eu
CognitoUserPoolId: eu-west-482rfhuhu23y
Mappings:
  Functions:
    'get-pets-list':
      ServiceLang: javascript
      ServiceName: pets-service
      ServiceModel: pets
      OperationName: getPets